### PR TITLE
Issue/164

### PR DESCRIPTION
**Pull request by kakarda653**
https://github.com/letsdoitworld/World-Cleanup-Day/issues/164

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
LGTM

**Comment by anastasiiaguzyeyeva** [comment]
Can you please provide the API documentation?

**Comment by kakarda653** [comment]
API:
Parameters:
date=[string] - YYYY-MM-DD format
countryCode=[string] - country code (i.e LI, US, UK etc.)
teamName=[string]

Endpoints:
### /trashpoints
**Method**: GET
**Parameters** **(optional)**: from=[date], to=[date], country=[countryCode]
**Response**: List of reports ordered by lastUpdateDate
**Example**:
_request_: `/trashpoints?from=2018-05-13&to=2018-05-22&country=US`
_response_: 
```
{
    "trashpoints": [
        {
            "hashtags": [],
            "composition": [
                "furniture"
            ],
            "location": {
                "latitude": 37.78532173373655,
                "longitude": -122.40652894601226
            },
            "status": "regular",
            "name": "Market Street 830",
            "address": "830 Market St, San Francisco, CA 94102, USA",
            "amount": "cartload",
            "datasetId": "96338702-64d9-4b59-8fb3-55065603ee3e",
            "areas": [
                "US",
                "US.CA",
                "US.CA.SF"
            ],
            "counter": 1,
            "updatedAt": "2018-05-21T15:39:15.857Z",
            "updatedBy": "1541254915996758",
            "createdAt": "2018-05-21T15:39:09.281Z",
            "createdBy": "1541254915996758",
            "id": "8a42fb43-f6b7-435d-b4ef-a659e1b8f859"
        },
        ...
```

### /users/list
**Method**: GET
**Parameters (optional)**: from=[date], to=[date], country=[countryCode]
**Response**: List of users without sensitive data (passwords, emails) with general statistics (number of trashpoints reported by status) ordered by joining date
**Example**:
_request_: `/users/list?from=2018-05-10&to=2018-05-23&country=US`
_response_: 
```
{
    "users": [
        {
            "id": "1541254915996758",
            "country": "US",
            "trashpoints": {
                "threat": 0,
                "regular": 2,
                "cleaned": 0,
                "outdated": 0
            }
        }
    ]
}
```

### /teams/list
**Method**: GET
**Parameters** (optional): from=[date], to=[date], nameTeam=[teamName]
**Response**: List of teams with general statistics (number of participants, number of trashpoints (by status)
**Example**:
_request_: `/teams/list?nameTeam=Mapping for Peace&to=2018-05-24`
_response_:
```
[
    {
        "id": "3b61c81a-2b8e-11e8-b467-0ed5f89f718f",
        "name": "Mapping for Peace",
        "members": 0,
        "trashpoints": 0,
        "groupCount": {}
    }
]
```

**Comment by KristiinaKerge** [comment]
@kakarda653 @aleksandr-wemakesoftware please take a look of these conflicts

**Comment by lynxlynxlynx** [comment]
some issues noted here (harder to find than this PR): https://github.com/letsdoitworld/World-Cleanup-Day/pull/296

**Pull request closed without merging**
